const getters = {
    AUTHENTICATION_GET_CURRENT_USER: "AUTHENTICATION_GET_CURRENT_USER",
    AUTHENTICATION_IS_USER_LOGGED_CORRECT: "AUTHENTICATION_IS_USER_LOGGED_CORRECT",
    AUTHENTICATION_IS_LOG_PROCESS: "AUTHENTICATION_IS_LOG_PROCESS",
    AUTHENTICATION_GET_JWT_TOKEN: "AUTHENTICATION_GET_JWT_TOKEN",

    DICT_GET_INPUT_SENSORS: "DICT_GET_INPUT_SENSORS",
    DICT_GET_OUTPUT_SENSORS: "DICT_GET_OUTPUT_SENSORS"
};

const mutations = {
    AUTHENTICATION_UPDATE_LOG_PROCESS: "AUTHENTICATION_UPDATE_LOG_PROCESS",
    AUTHENTICATION_LOGOUT: "AUTHENTICATION_LOGOUT",
    AUTHENTICATION_UPDATE_CURRENT_USER: "AUTHENTICATION_UPDATE_CURRENT_USER",
    AUTHENTICATION_SET_STATE_TO_LOGGED: "AUTHENTICATION_SET_STATE_TO_LOGGED",
    AUTHENTICATION_LOGIN_FAILED: "AUTHENTICATION_LOGIN_FAILED",

    ALERT_FAILED_LOGIN: "ALERT_FAILED_LOGIN",
    ALERT_SUCCESS_LOGIN: "ALERT_SUCCESS_LOGIN",

    DICT_SET_INPUT_SENSORS: "DICT_SET_INPUT_SENSORS",
    DICT_SET_OUTPUT_SENSORS: "DICT_SET_OUTPUT_SENSORS",
};

const actions = {
    AUTHENTICATION_LOGIN: "AUTHENTICATION_LOGIN",
    AUTHENTICATION_LOGOUT: "AUTHENTICATION_LOGOUT",

    DICT_GET_ALL_SENSOR_KINDS: "DICT_GET_ALL_SENSOR_KINDS",
};

export default {
    getters,
    actions,
    mutations
}
