const getters = {
    AUTHENTICATION_GET_CURRENT_USER: "AUTHENTICATION_GET_CURRENT_USER",
    AUTHENTICATION_IS_USER_LOGGED_CORRECT: "AUTHENTICATION_IS_USER_LOGGED_CORRECT",
    AUTHENTICATION_IS_LOG_PROCESS: "AUTHENTICATION_IS_LOG_PROCESS"
};

const mutations = {
    AUTHENTICATION_UPDATE_LOG_PROCESS: "AUTHENTICATION_UPDATE_LOG_PROCESS",
    AUTHENTICATION_LOGOUT: "AUTHENTICATION_LOGOUT",
    AUTHENTICATION_UPDATE_CURRENT_USER: "AUTHENTICATION_UPDATE_CURRENT_USER",
    AUTHENTICATION_SET_STATE_TO_LOGGED: "AUTHENTICATION_SET_STATE_TO_LOGGED",
    AUTHENTICATION_LOGIN_FAILED: "AUTHENTICATION_LOGIN_FAILED",

    ALERT_FAILED_LOGIN: "ALERT_FAILED_LOGIN",
    ALERT_SUCCESS_LOGIN: "ALERT_SUCCESS_LOGIN"
};

const actions = {
    AUTHENTICATION_LOGIN: "AUTHENTICATION_LOGIN",
    AUTHENTICATION_LOGOUT: "AUTHENTICATION_LOGOUT"
};

export default {
    getters,
    actions,
    mutations
}
